name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: wmuj
          base: header, activity, repositories, metadata
          config_timezone: Asia/Shanghai
          optimize: svg
          experimental_features: --optimize-svg

          # 日历热力图
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          # 编程语言统计
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 5

          # 代码行数统计
          plugin_lines: yes

          # WakaTime（精简版）
          plugin_wakatime: yes
          plugin_wakatime_days: 7
          plugin_wakatime_limit: 4
          plugin_wakatime_sections: time, languages
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: wmuj
